// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./.vitepress/theme/components/audio-player.vue')['default']
    CarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    CarbonArrowRight: typeof import('~icons/carbon/arrow-right')['default']
    CarbonArrowUp: typeof import('~icons/carbon/arrow-up')['default']
    CarbonChevronRight: typeof import('~icons/carbon/chevron-right')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    FavList: typeof import('./.vitepress/theme/components/fav/list.vue')['default']
    FluentStarOff24Regular: typeof import('~icons/fluent/star-off24-regular')['default']
    IonIosSunny: typeof import('~icons/ion/ios-sunny')['default']
    LaArrowUp: typeof import('~icons/la/arrow-up')['default']
    LaCamera: typeof import('~icons/la/camera')['default']
    LaEye: typeof import('~icons/la/eye')['default']
    LaEyeSlash: typeof import('~icons/la/eye-slash')['default']
    LangToggle: typeof import('./.vitepress/theme/components/lang-toggle.vue')['default']
    LaStarSolid: typeof import('~icons/la/star-solid')['default']
    ListBooks: typeof import('./.vitepress/theme/components/list/books.vue')['default']
    ListLinks: typeof import('./.vitepress/theme/components/list/links.vue')['default']
    NavBar: typeof import('./.vitepress/theme/components/nav/bar.vue')['default']
    NavLinks: typeof import('./.vitepress/theme/components/nav/links.vue')['default']
    NewSantanaYantra: typeof import('./.vitepress/comps/new/santana-yantra.vue')['default']
    PageFooter: typeof import('./.vitepress/theme/components/page/footer.vue')['default']
    PageList: typeof import('./.vitepress/theme/components/page/list.vue')['default']
    PageParents: typeof import('./.vitepress/theme/components/page/parents.vue')['default']
    PageSiblings: typeof import('./.vitepress/theme/components/page/siblings.vue')['default']
    PanelDark: typeof import('./.vitepress/theme/components/panel/dark.vue')['default']
    PanelDock: typeof import('./.vitepress/theme/components/panel/dock.vue')['default']
    PanelFav: typeof import('./.vitepress/theme/components/panel/fav.vue')['default']
    PanelScroll: typeof import('./.vitepress/theme/components/panel/scroll.vue')['default']
    Santana2: typeof import('./.vitepress/comps/santana-2.vue')['default']
    SatYantra: typeof import('./.vitepress/comps/sat-yantra.vue')['default']
    ShivaSutraSans: typeof import('./.vitepress/comps/shiva-sutra/sans.vue')['default']
    ShivaSutraTrans: typeof import('./.vitepress/comps/shiva-sutra/trans.vue')['default']
    SvgSave: typeof import('./.vitepress/theme/components/svg/save.vue')['default']
    TopBar: typeof import('./.vitepress/theme/components/top-bar.vue')['default']
    YoutubeEmbed: typeof import('./.vitepress/theme/components/youtube-embed.vue')['default']
  }
}

export {}
